//import './assets/main.css'
import './style.css'

import { createPinia } from 'pinia'
import { createApp } from 'vue'

import App from './App.vue'
import router from './router'

//Font awesomo
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesRight,
  faAngleUp,
  faBars,
  faBarsStaggered,
  faBook,
  faBox,
  faBoxesStacked,
  faCalendar,
  faCartShopping,
  faChartLine,
  faCircleCheck,
  faCircleInfo,
  faCirclePlus,
  faClipboardList,
  faEarthAmericas,
  faEye,
  faFileInvoice,
  faGear,
  faHouse,
  faImages,
  faLayerGroup,
  faLink,
  faList,
  faListCheck,
  faLocationDot,
  faMagnifyingGlass,
  faMapLocationDot,
  faMinus,
  faPenToSquare,
  faPlus,
  faShield,
  faShop,
  faTags,
  faTrashCan,
  faTruckFast,
  faUser,
  faWarehouse,
  faXmark,
  faLocationArrow,
  faLocationCrosshairs,
  faBarcode,
  faDownload,
  faEyeSlash,
  faLock,
  faHeadset,
  faSpinner,
  faStar,
  faClock,
  faCreditCard,
  faPen,
  faMoneyBill1,
  faCashRegister,
  faReceipt,
  faUserTie,
  faUsers,
  faUserGroup,
  faPaperPlane,
  faArrowRotateLeft,
  faCartArrowDown,
  faDolly,
  faFileExport,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
library.add(
  faBarsStaggered,
  faChartLine,
  faLayerGroup,
  faTags,
  faAngleRight,
  faCircleInfo,
  faPenToSquare,
  faList,
  faBoxesStacked,
  faAngleUp,
  faAngleDown,
  faBox,
  faBook,
  faListCheck,
  faTrashCan,
  faEye,
  faGear,
  faCirclePlus,
  faClipboardList,
  faWarehouse,
  faShop,
  faLink,
  faFileInvoice,
  faImages,
  faCalendar,
  faMagnifyingGlass,
  faCartShopping,
  faUser,
  faBars,
  faAnglesRight,
  faXmark,
  faAngleLeft,
  faHouse,
  faPlus,
  faMinus,
  faTruckFast,
  faCircleCheck,
  faShield,
  faMapLocationDot,
  faEarthAmericas,
  faLocationDot,
  faLocationArrow,
  faLocationCrosshairs,
  faBarcode,
  faDownload,
  faEyeSlash,
  faLock,
  faHeadset,
  faSpinner,
  faStar,
  faClock,
  faCreditCard,
  faPen,
  faMoneyBill1,
  faCashRegister,
  faReceipt,
  faUserTie,
  faUsers,
  faUserGroup,
  faPaperPlane,
  faArrowRotateLeft,
  faCartArrowDown,
  faDolly,
  faFileExport,
  faTriangleExclamation,
)

import { faFacebookF, faInstagram, faBilibili } from '@fortawesome/free-brands-svg-icons'
library.add(faFacebookF, faInstagram, faBilibili)

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.component('font-awesome-icon', FontAwesomeIcon)
app.mount('#app')
